"""Render a Kenya NTLD-P TB notification as a PDF.

Uses reportlab (pure-Python, no system dependencies) with built-in fonts
(Helvetica) so the image stays slim. Output is a BytesIO buffer — nothing
touches disk.

Layout mirrors the Kenya NTLD-P case-based notification tool:
  - Top header: Ministry of Health / NTLD-P title block
  - Facility block: KMFL code, facility name, county, date
  - Patient block: names, DOB, sex, contact, UPI
  - Disease block: site, classification, drug resistance, ICD-10
  - Diagnostics block: GeneXpert / AFB smear / chest X-ray results
  - HIV block: status, CD4, VL, ART, CPT
  - Treatment block: regimen, start date, phase, DOT supporter
  - Notifier block: name, role, date, signature line
  - Footer: form metadata (generated by DaktariTB)

We deliberately avoid MOH's official logo — building on top of public NTLD-P
form structure is fine, reproducing their crest is not.
"""

from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from daktaritb_mcp.kenya_moh.tb_notification import TbNotification


def _styles():
    base = getSampleStyleSheet()
    return {
        "header": ParagraphStyle(
            name="Header",
            parent=base["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=13,
            alignment=1,  # center
            spaceAfter=2,
        ),
        "subheader": ParagraphStyle(
            name="Subheader",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=9,
            alignment=1,
            spaceAfter=8,
        ),
        "section": ParagraphStyle(
            name="Section",
            parent=base["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=colors.white,
            backColor=colors.HexColor("#0F766E"),
            leading=14,
            leftIndent=4,
            spaceBefore=6,
            spaceAfter=2,
        ),
        "body": ParagraphStyle(
            name="Body",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=9,
            leading=11,
        ),
        "label": ParagraphStyle(
            name="Label",
            parent=base["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
        ),
        "value": ParagraphStyle(
            name="Value",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=9,
            leading=11,
        ),
        "footer": ParagraphStyle(
            name="Footer",
            parent=base["BodyText"],
            fontName="Helvetica-Oblique",
            fontSize=7,
            textColor=colors.HexColor("#6B7280"),
            alignment=1,
        ),
    }


def _fv(label: str, value: str) -> list:
    """Return [label-para, value-para] for a 2-cell row."""
    S = _styles()
    return [
        Paragraph(label, S["label"]),
        Paragraph(value or "—", S["value"]),
    ]


def _pair_table(rows: list[list]) -> Table:
    """Build a 2-column table of label/value pairs."""
    tbl = Table(rows, colWidths=[55 * mm, 115 * mm])
    tbl.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#E5E7EB")),
            ]
        )
    )
    return tbl


def _yes_no(val: bool) -> str:
    return "Yes" if val else "No"


def _section(title: str) -> Paragraph:
    return Paragraph(title, _styles()["section"])


def render_pdf(notification: TbNotification) -> bytes:
    """Render the notification as a PDF. Returns the raw PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
        title="Kenya NTLD-P TB Notification",
        author="DaktariTB MCP Agent",
    )
    S = _styles()
    story: list = []

    # --- Header ---
    story.append(Paragraph("REPUBLIC OF KENYA — MINISTRY OF HEALTH", S["subheader"]))
    story.append(
        Paragraph(
            "National Tuberculosis, Leprosy and Lung Disease Programme (NTLD-P)",
            S["header"],
        )
    )
    story.append(
        Paragraph("TB Case Notification (TB-001 equivalent)", S["subheader"])
    )
    story.append(Spacer(1, 4 * mm))

    # --- Facility ---
    story.append(_section("1. NOTIFYING FACILITY"))
    f = notification.facility
    story.append(
        _pair_table(
            [
                _fv("KMFL code", f.kmfl_code),
                _fv("Facility name", f.name),
                _fv("County", f.county),
                _fv("Sub-county", f.sub_county),
            ]
        )
    )

    # --- Patient ---
    story.append(_section("2. PATIENT INFORMATION"))
    p = notification.patient
    full_name = f"{p.given_name} {p.family_name}".strip() or "—"
    age_display = f"{p.age_years}" if p.age_years is not None else "—"
    story.append(
        _pair_table(
            [
                _fv("Name (Given, Family)", full_name),
                _fv("Sex", p.sex.capitalize() or "—"),
                _fv("Date of birth", p.date_of_birth),
                _fv("Age (years)", age_display),
                _fv("UPI / identifier", p.upi),
                _fv("Town / city", p.address_city),
                _fv("Phone", p.phone),
            ]
        )
    )

    # --- Disease ---
    story.append(_section("3. TB DISEASE CLASSIFICATION"))
    d = notification.disease
    story.append(
        _pair_table(
            [
                _fv("Anatomical site", d.site.replace("_", " ").capitalize()),
                _fv("Bacteriological status", d.bacteriological_status.replace("_", " ").capitalize()),
                _fv("Case type", d.case_type.replace("_", " ").capitalize()),
                _fv("Drug resistance", d.drug_resistance_status.replace("_", " ").capitalize()),
                _fv("Onset / diagnosis date", d.onset_date),
                _fv("ICD-10 code", d.icd10_code),
                _fv("Description", d.description),
            ]
        )
    )

    # --- Diagnostics ---
    story.append(_section("4. DIAGNOSTIC FINDINGS"))
    dx = notification.diagnostic_findings
    story.append(
        _pair_table(
            [
                _fv("GeneXpert MTB/RIF", f"{dx.genexpert_result}" + (f"  ({dx.genexpert_date})" if dx.genexpert_date else "")),
                _fv("AFB sputum smear", f"{dx.afb_smear_result}" + (f"  ({dx.afb_smear_date})" if dx.afb_smear_date else "")),
                _fv("Chest X-ray", dx.chest_xray_result),
                _fv("Culture", dx.culture_result),
            ]
        )
    )

    # --- HIV ---
    story.append(_section("5. TB/HIV INTEGRATION"))
    h = notification.hiv
    cd4_display = f"{int(h.cd4_count)} cells/µL" + (f"  ({h.cd4_date})" if h.cd4_date else "") if h.cd4_count is not None else "—"
    vl_display = f"{int(h.viral_load)} copies/mL" + (f"  ({h.viral_load_date})" if h.viral_load_date else "") if h.viral_load is not None else "—"
    story.append(
        _pair_table(
            [
                _fv("HIV status", h.status.capitalize()),
                _fv("CD4 count", cd4_display),
                _fv("HIV viral load", vl_display),
                _fv("On antiretroviral therapy (ART)", _yes_no(h.on_art)),
                _fv("ART regimen", h.art_regimen),
                _fv("ART start date", h.art_start_date),
                _fv("Cotrimoxazole preventive therapy", _yes_no(h.cotrimoxazole_preventive_therapy)),
            ]
        )
    )

    # --- Treatment ---
    story.append(_section("6. TB TREATMENT"))
    t = notification.treatment
    story.append(
        _pair_table(
            [
                _fv("Treatment regimen", t.regimen),
                _fv("Start date", t.start_date),
                _fv("Current phase", t.phase.capitalize()),
                _fv("DOT supporter", t.dot_supporter_name),
                _fv("Relation to patient", t.dot_supporter_relation),
                _fv("DOT supporter phone", t.dot_supporter_phone),
            ]
        )
    )

    # --- Notifier ---
    story.append(_section("7. NOTIFICATION AUTHORIZATION"))
    n = notification.notifier
    story.append(
        _pair_table(
            [
                _fv("Notified by", n.name),
                _fv("Role", n.role),
                _fv("Notification date", n.date),
                _fv("Signature", "_________________________"),
            ]
        )
    )

    # --- Missing fields warning (if any) ---
    if notification.missing_fields:
        story.append(Spacer(1, 4 * mm))
        missing_para = Paragraph(
            "<b>Fields requiring manual completion:</b> "
            + ", ".join(notification.missing_fields)
            + ". Review before submission to TIBU.",
            ParagraphStyle(
                name="Warn",
                fontName="Helvetica-Oblique",
                fontSize=9,
                textColor=colors.HexColor("#B45309"),
                leading=12,
            ),
        )
        story.append(missing_para)

    # --- Footer ---
    story.append(Spacer(1, 6 * mm))
    story.append(
        Paragraph(
            f"Generated by DaktariTB MCP Agent on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}. "
            "This document is a clinical decision support output; submission to the TIBU "
            "surveillance system requires review and authorization by a registered clinician.",
            S["footer"],
        )
    )

    doc.build(story)
    return buf.getvalue()
